# For save directories only enter the parent directory for all projects checkpoints. 
# project.name will be joined to both checkpoints and runs as the basename directory.
project:
    name:              'face_inanimate_400k_seed'
    description:       'Training VGG on cars.'
    num_tasks:         1 
architecture:
    model:             'vgg16'
data:  
    task1:            '/raid/katha/datasets/data_car'
max_samples:
    train:             {"data_car":45}
    valid:             {"data_car":5}
save_directories:
    checkpoints_dir:  '/raid/pranjul/home/pranjul/transfer/modified_model/'
    log_dir:          '/home/pranjul/BranchingNets_updated/lesioning/runs/'
saving:
    keep:             [-1]
    function:         'step'
    params:           {'step': 10, 'offset': 0}
    max_count:        100
hyperparameters:
    batch_size:       128
    optimizer:        'sgd'
    momentum:         0.9
    learning_rate:    0.001
    use_scheduler:    True
    scheduler:        'ReduceLROnPlateau'
    scheduler_params: {'patience': 10, 'verbose': True}
    weight_decay:     0.0001
    split:            False
